# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Analyze project with Jtest
    
    permissions:
      # required for all workflows
      security-events: write

    runs-on: self-hosted

    steps:
    - name: Checkout Parabnk project
      uses: actions/checkout@v4
    - name: Create input for Jtest
      run: mvn clean install jtest:jtest -s C:/actions_runner/git/settings.xml -Djtest.skip=true
    - name: Run Jtest
      id: jtest
      uses: parasoft/run-jtest-action@2.0.2
      with:
        #Uses the jtest.data.json generated with the Maven command in the previous step
        input: target/jtest/jtest.data.json

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive

